### ISSUE TITLE
TypeError: Cannot read property 'paper-button' of undefined

### ISSUE THREAD

**Issue by nalbion** [bsorrentino/generator-polymerts#2]
```
 $ yo polymerts:gen paper-button
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'paper-button' of undefined
    at Gen.parse (/usr/lib/node_modules/generator-polymerts/gen/index.js:19:48)
    at /usr/lib/node_modules/generator-polymerts/node_modules/yeoman-generator/lib/base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)

$ yo --version
1.6.0
$ node --version
v5.4.0
$ npm --version
3.5.3
$ grep version /usr/lib/node_modules/generator-polymerts/package.json 
  "version": "0.4.3"
$ ls bower_components/paper-button/paper-button.html 
bower_components/paper-button/paper-button.html
```

**Comment by nalbion** [comment]
works for `sudo npm install -g generator-polymerts@0.4.2`
